mclaren570sgt4
samkatakouzinosracing/nspace.hu-soundshift pull request #37
Opened 2021-03-11 22:25 UTC by Fuzzwah

Added the mclaren570sgt4, also sorted cars alphabetical

2021-03-15 14:29 UTC, samkatakouzinos requested changes
Please see review entries. 
RPM changes are ok. 
Alias changes I wouldn't accept unless you provide reason to do so.

2021-03-15 14:29 UTC, samkatakouzinos commented on vehicles.ini
> +c8rvettegte,Chevrolet Corvette C8.R,6,6800
Alias please revert or provide reason
RPM is ok
```suggestion
c8rvettegte,Chevrolet Corvette C8.R GTE,6,6800
```

2021-03-15 14:29 UTC, samkatakouzinos commented on vehicles.ini
> +dallarair01,Dallara iR01,7,19000
Alias please revert or provide reason
RPM is ok
```suggestion
dallarair01,Dallara iR-01,7,19000
```

2021-03-15 14:29 UTC, samkatakouzinos commented on vehicles.ini
> +indypropm18,Indy Pro PM-18,6,8650
Alias please revert or provide reason
```suggestion
indypropm18,Indy Pro 2000 PM-18,6,8650
```

2021-03-15 14:29 UTC, samkatakouzinos commented on vehicles.ini
> +lamborghinievogt3,Lamborghini Huracan GT3 EVO,6,8000
Alias please revert or provide reason
RPM is ok
```suggestion
lamborghinievogt3,Lamborghini Huracán GT3 EVO,6,8000
```

2021-03-15 14:29 UTC, samkatakouzinos commented on vehicles.ini
> +bmwm4gt3,BMW M4 GT3,6,6650
RPM is ok

2021-03-15 14:29 UTC, samkatakouzinos commented on vehicles.ini
> +dallarap217,Dallara P217,6,8250
RPM is ok

2021-03-15 14:29 UTC, samkatakouzinos commented on vehicles.ini
> +mclaren570sgt4,McLaren 570s GT4,7,7125
Add vehicle is ok

2021-03-18 05:46 UTC, samkatakouzinosracing commented on vehicles.ini
> +mclaren570sgt4,McLaren 570s GT4,7,7125
Vehicle added by #38 and #40

2021-03-18 05:49 UTC, samkatakouzinosracing commented
Closing. Intent to add vehicle now done by #38

2021-03-18 05:49 UTC, closed without merging